version: "3"
services:
  api:
    container_name: myapi
    build: backend/.
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    networks:
      #user-defined network bridge for all containers
      - frontend
      - backend

  app:
    container_name: myapp
    build: frontend/.
    command: "streamlit run app.py --server.enableCORS false overview.py"
    ports:
      - "8080:8080"
    networks:
      - frontend
  # db:
  #   image: postgres:13.1
  #   environment:
  #       POSTGRES_PASSWORD: verysecret
  #   networks:
  #     - backend
networks:
  frontend:
  backend:


  