name: End-to-end tests

on: [push]

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: Activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          source venv/bin/activate
          pip install playwright
          playwright install chromium
          docker-compose build
          
      - name: Run application
        run: |
          docker-compose up -d
          sleep 10
          source venv/bin/activate
          pytest test_end_to_end/test_frontend.py
